// Real carta data — copy verbatim from indomitocafe.com/carta
// (no prices/items invented; descriptions bilingual ES/EN kept as written)

const CARTA_DATA = {
  intro: { kicker: 'Nuestra carta', title: 'CAFÉ' },
  bebidas: [
    { name:'Espresso',        price:'$4300', recipe:'40ml · 89°c · 25–30 seg',
      es:['Intenso y directo.','Sin concesiones.'],
      en:['Bold and direct.','No compromise.'] },
    { name:'Doble Espresso',  price:'$4300', recipe:'2 × 40ml · 89°c',
      es:['Profundo, aromático.','Para ir más lejos.'],
      en:['Deep, aromatic.','For those who go further.'] },
    { name:'Long Black',      price:'$4300', recipe:'40ml espresso + 90ml agua · 89°c',
      es:['Suavizado, no diluido.','Cuerpo intacto.'],
      en:['Softened, not diluted.','Body intact.'] },
    { name:'Magic',           price:'$4800', recipe:'40ml espresso + 80ml leche texturizada',
      es:['Balance preciso.','Presencia silenciosa.'],
      en:['Precise balance.','Quiet presence.'] },
    { name:'Flat White',      price:'$5000', recipe:'40ml espresso + 120ml leche texturizada',
      es:['Cremoso y firme.','Clásico sin exceso.'],
      en:['Creamy and steady.','Classic, restrained.'] },
    { name:'Latte',           price:'$5000', recipe:'30ml espresso + 180ml leche texturizada',
      es:['Abierto, suave.','Café en calma.'],
      en:['Open and soft.','Coffee at ease.'] },
  ],
  frios: [
    { name:'Ice Flat',        price:'$5200', recipe:'40ml espresso · 120ml leche fría',
      es:['Espresso frío, leche sedosa.','Preciso. Seco.'],
      en:['Cold espresso, silky milk.','Precise. Dry.'] },
    { name:'Ice Latte',       price:'$5200', recipe:'30ml espresso · 180ml leche fría',
      es:['Más leche, menos gesto.','Frío. Suave.'],
      en:['More milk, less gesture.','Cold. Soft.'] },
    { name:'Ice Americano',   price:'$5000', recipe:'40ml espresso · agua fría',
      es:['Espresso y agua fría.','Claro. Directo.'],
      en:['Espresso with cold water.','Clear. Direct.'] },
    { name:'Espresso Tonic',  price:'$5500', recipe:'40ml espresso · tónica fría',
      es:['Café y burbuja.','Amargo tenso.'],
      en:['Coffee and bubbles.','Sharp bitterness.'] },
    { name:'Cold Brew / Orange', price:'$5500', recipe:'infusión en frío · extracción lenta',
      es:['Tiempo, no presión.','Frío. Continuo.'],
      en:['Cold infusion, slow extraction.','Cold. Continuous.'] },
  ],
  filtrados: [
    { name:'Chemex / Origami', price:'$5600', recipe:'40ml espresso · 120ml leche fría',
      es:['Extracción limpia.','Claridad y pausa.'],
      en:['Clean extraction.','Clarity and pause.'] },
  ],
  alcohol: [
    { name:'Carpano / Orange', price:'$6000', recipe:null,
      es:['Amargo clásico.','Cítrico seco.'],
      en:['Classic bitterness.','Dry citrus.'] },
    { name:'Cerveza',          price:'$3500', recipe:null,
      es:['Fría. Directa.'],
      en:['Cold. Straightforward.'] },
  ],
  pasteleria: [
    { name:'Scones de queso',          sub:'Cheese Scones',   price:'$1800',
      es:['Salino, denso.','Acompaña bien.'], en:['Savory, dense.','Pairs well.'] },
    { name:'Palmeritas',               sub:'Palmier Cookies', price:'$2000',
      es:['Crujientes.','Azúcar justo.'],     en:['Crisp.','Balanced sugar.'] },
    { name:'Medialunas',               sub:'Croissants',      price:'$1500',
      es:['Manteca, hojaldre.','Clásico porteño.'], en:['Butter, layers.','Buenos Aires classic.'] },
    { name:'Cookies veganas',          sub:'Vegan Cookies',   price:'$1800',
      es:['Textura firme.','Dulzor contenido.'], en:['Firm texture.','Measured sweetness.'] },
    { name:'Lemon Muffins',            sub:null,              price:'$1600',
      es:['Ácido leve.','Final fresco.'],      en:['Gentle acidity.','Fresh finish.'] },
    { name:'Rolls de Canela',          sub:'Cinnamon Roll',   price:'$2000',
      es:['Especiado suave.','Calor lento.'],  en:['Soft spice.','Slow warmth.'] },
  ],
  manifesto: {
    es1: 'Extraemos nuestro café a 89°c',
    es2: 'para preservar su equilibrio.',
    en1: 'We extract our coffee at 89°c',
    en2: 'to preserve its balance.',
  },
};

export { CARTA_DATA };
